name = "DomainIntegrals"
uuid = "cc6bae93-f070-4015-88fd-838f9505a86c"
authors = ["Daan Huybrechs <daan.huybrechs@cs.kuleuven.be>"]
version = "0.1.1"

[deps]
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
